### ISSUE TITLE
write up how PaDEL is compiled

### ISSUE THREAD

**Issue by egonw** [cdk/PaDEL-Descriptor#4]
So that we can then use this information to create a GitHub Action: https://github.com/cdk/PaDEL-Descriptor/issues/3

**Comment by egonw** [comment]
@RvdPloeg, do you have an update on this?

**Comment by RvdPloeg** [comment]
a readme file is add that describes how to run PaDEL from the terminal.

**Comment by egonw** [comment]
I added some Markdown styling.
